version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"  # Exponemos el backend en el 3000 como pide la guía
    volumes:
      - ./backend:/app  # Guarda tu bbdd.json y actualiza el código en vivo
    environment:
      - FLASK_ENV=development

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80" # Tu frontend estará en http://localhost:8080
    volumes:
      - ./frontend:/usr/share/nginx/html